### ISSUE TITLE
Github Swag Order Delivery

### ISSUE THREAD

**Issue by drqasimali** [pranavavva/pranavavva#1]
Hy,

I have requested for a swag order for my students before 15 days and wang to know about the maximum delivery time to receive the swag. Can you please let me know that it took how much time ti deliver your swag?

Regards,
Dr. Qasim Ali
University of Engineering and Technology Lahore

**Comment by pranavavva** [comment]
I live in New Jersey and it took around a week for the swag to reach me. If you are outside the US, I believe you will have to wait longer. I'd suggest you open an issue on [the graduation repository](https://github.com/education/graduation).

**Comment by drqasimali** [comment]
Dead Pranavavva,

I am unable to reply their because your given case has been archived. Where can I contact for my problem?

Regards,
Dr.Qasim Ali

________________________________

**Comment by pranavavva** [comment]
I'm sorry but I don't know. I'm just a student haha. Maybe there is an email on that repo that you can contact. Best of luck!!

**Comment by drqasimali** [comment]
Dear,,

Thank you so much for your reply and guidance.

________________________________
